### PR TITLE
:art: Moved CSS and formatted HTML

### PR DESCRIPTION
**Pull request by daanbreur**

### CODE REVIEW

**Comment by daanbreur** [comment]
@mitxela i hope this helps ;) just a little start will do more of this later

**Comment by mitxela** [comment]
just whitespace changes? I appreciate the effort, but I'd much rather be seeing pull requests for new algorithms...

**Comment by mitxela** [comment]
I'd rather not split the CSS out. Up to a certain size, a monolithic source file is a lot clearer. I chucked the input-range stuff into a separate file only because after constructing that monstrosity, I don't want to look at it ever again.

**Comment by daanbreur** [comment]
Okey :D

**Pull request closed without merging**
